#!/bin/bash
sleep 5
audio_sink=0
name=$(sed 's/\"//g' <<< $NAME)

#exit if not a BT address
if [[ ! $name =~ ^([0-9A-F]{2}[:-]){5}([0-9A-F]{2})$ ]]; then exit 0;  fi

# PulseAudio bluetooth sources now have a .a2dp_source suffix
audio_source=bluez_source.$(sed 's/:/_/g' <<< $name).a2dp_source

action=$(expr "$ACTION" : "\([a-zA-Z]\+\).*")
if [ "$action" = "add" ]; then
    logger "[$(basename $0)] Bluetooth device is being added [$name]"
    logger "[$(basename $0)] Patching $audio_source into ALSA sink #$audio_sink"
    # loop back this source to the default sink
    handle=$(pactl load-module module-loopback source=$audio_source sink=$audio_sink)
    if [ -z $handle ]
    then
        logger "[$(basename $0)] Failed to load loopback module on sink $audio_sink"
	audio_sink=1
    	logger "[$(basename $0)] Patching $audio_source into ALSA sink #$audio_sink"
        handle=$(pactl load-module module-loopback source=$audio_source sink=$audio_sink)
	if [ -z $handle ]
	then
	    logger "[$(basename $0)] Failed to load loopback module on sink $audio_sink"
	    logger "[$(basename $0)] Loopback module not loaded. Playback not possible."
	else
	    logger "[$(basename $0)] PulseAudio module-loopback returned handle [$handle]"
	fi
    else
	logger "[$(basename $0)] PulseAudio module-loopback returned handle [$handle]"
    fi
fi

if [ "$action" = "remove" ]; then
    logger "[$(basename $0)] Bluetooth device is being removed [$name]"
    # remove any loopback modules assigned to this source
    # only required for USB sound cards, which PulseAudio will not automatically remove
    for handle in $(pactl list short modules | grep module-loopback | grep source=$audio_source | cut -f 1); do
        logger "[$(basename $0)] Unloading module-loopback with handle [$handle]"
        pactl unload-module $handle
    done
fi

